# Generated by Django 3.2.6 on 2022-04-10 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_coin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_coin',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
