# Generated by Django 3.2.6 on 2022-04-10 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_coin_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_coin',
            name='email',
        ),
    ]
