# Generated by Django 3.2.6 on 2022-04-10 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_coin_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_coin',
            name='created_data',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
