# Generated by Django 3.2.6 on 2022-04-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(upload_to='books/img')),
                ('file', models.FileField(upload_to='books/file')),
                ('coin', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('download_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('created_data', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
