# Generated by Django 3.2.6 on 2022-04-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_books_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='img',
            field=models.ImageField(default='books/img/img.jpg', upload_to='books/img'),
        ),
    ]
