# Generated by Django 3.2.6 on 2022-04-09 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_books_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='description',
            new_name='title',
        ),
    ]
