# Generated by Django 3.2.6 on 2022-04-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_books_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='file',
            field=models.FileField(default='books/file/file.pdf', upload_to='books/file'),
        ),
    ]
