# Generated by Django 3.2.6 on 2022-04-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_books_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='name',
            field=models.CharField(blank=True, default='kitob', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
