# Generated by Django 3.2.6 on 2022-04-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20220408_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='tag',
            field=models.TextField(blank=True, null=True),
        ),
    ]
