# Generated by Django 3.2.6 on 2022-04-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_books_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='view',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
