# Generated by Django 3.2.6 on 2022-04-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_books_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
