# Generated by Django 3.2.6 on 2022-04-10 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_books_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='file',
            field=models.FileField(default='books/file/file.pdf', upload_to='books/books'),
        ),
    ]
