# Generated by Django 3.2.6 on 2022-04-13 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_books_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='star',
            field=models.PositiveIntegerField(blank=True, default=3, null=True),
        ),
    ]
