# Generated by Django 3.2.6 on 2022-04-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_search_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='search_word',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
