# Generated by Django 3.2.6 on 2022-04-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_search_word_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search_word',
            name='count',
        ),
        migrations.AddField(
            model_name='search_word',
            name='count_search',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
