# Generated by Django 3.2.6 on 2022-04-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_alter_search_word_count_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('count_search', models.PositiveIntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Search_Word',
            new_name='Search_Book',
        ),
    ]
