# Generated by Django 3.2.6 on 2022-04-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='filestore-blogs', max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='filestore-blogs-description', null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='blogs/img')),
                ('download_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('created_data', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('tag', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
