# Generated by Django 3.2.6 on 2022-04-10 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='download_count',
            new_name='view',
        ),
    ]
