# Generated by Django 3.2.6 on 2022-04-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_file_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='tag',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.TextField(blank=True, default='filestore.uz', null=True),
        ),
    ]
