# Generated by Django 3.2.6 on 2022-04-10 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20220409_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, default='file', max_length=300, null=True),
        ),
    ]
