# Generated by Django 3.2.6 on 2022-04-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_file_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
