# Generated by Django 3.2.6 on 2022-04-10 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_alter_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(default='books/file/file.pdf', upload_to='books/files'),
        ),
    ]
