# Generated by Django 3.2.6 on 2022-04-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='img',
            field=models.ImageField(default='img.png', upload_to='books/img'),
        ),
    ]
